pipeline {
    agent any

    environment {
        TYK_DASH_URL = credentials('tyk-dash-url')
        TYK_ORG_ID = credentials('tyk-org-id')
        TYK_DASH_SECRET = credentials('tyk-dash-secret')
        TYK_PROD_DASH_URL = credentials('tyk-prod-dash-url')
        TYK_PROD_DASH_SECRET = credentials('tyk-prod-dash-secret')
        TYK_SYNC_PATH = credentials('tyk-sync-path')
    }

    stages {
        stage('test') {
            steps {
                echo 'tests running'
                sh env.TYK_SYNC_PATH + 'tyk-sync sync --dashboard ' + env.TYK_DASH_URL + ' --secret ' + env.TYK_DASH_SECRET + ' --path="./dump" --test'
                script {
                    def apiDefs = findFiles(glob: './../dump/api-*.json')

                    apiDefs.each { apiDef ->
                        def pJson = readJSON file: env.WORKSPACE + "/" + apiDef.name
                        sh "echo Testing ${pJson.name}: ${pJson.api_id}"

                        assert pJson.use_keyless == false
                    }
                }
            }
        }
        stage('deploy') {
            when {
                expression { env.BRANCH_NAME == 'master' }
            }
            steps {
                echo "Deploying, because we are on ${env.BRANCH_NAME}"
                sh "${env.TYK_SYNC_PATH}tyk-sync sync --dashboard ${env.TYK_DASH_URL} --secret ${env.TYK_DASH_SECRET} --path ./dump"
            }
        }
        stage('deploy-prod') {
            when { tag "release-*" }
            steps {
                echo "Deploying to production because we have new tag"
                sh "${env.TYK_SYNC_PATH}tyk-sync sync --dashboard ${env.TYK_PROD_DASH_URL} --secret ${env.TYK_PROD_DASH_SECRET} --path ./dump"
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}
