pipeline {
    agent any

    environment {
        TYK_DASH_URL = credentials('tyk-dash-url')
        TYK_ORG_ID = credentials('tyk-org-id')
        TYK_DASH_SECRET = credentials('tyk-dash-secret')
        TYK_SYNC_PATH = credentials('tyk-sync-path')
    }

    stages {
        stage('test') {
            steps {
                echo 'tests running'
                sh "./gitops.sh sync_test"
                script {
                    def apiDefs = findFiles(glob: './../dump/api-*.json')

                    apiDefs.each { apiDef ->
                        def pJson = readJSON file: env.WORKSPACE + "/" + apiDef.name
                        sh "echo Testing ${pJson.name}: ${pJson.api_id}"

                        assert pJson.use_keyless == false
                    }
                }
            }
        }
        stage('deploy') {
            when {
                expression { env.BRANCH_NAME == 'master' }
            }
            steps {
                echo "Deploying, because we are on ${env.BRANCH_NAME}"
                sh "wget https://github.com/asoorm/tyk-git/releases/download/0.1-alpha/tyk-git"
                sh "chmod +x tyk-git"
                sh "./tyk-git -h"
                sh "printenv"
                sh "env"
                // logic to pull credentials and use them to sync
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}
