pipeline {
    agent any

    environment {
        TYK_DASH_URL = credentials('tyk-dash-url')
        TYK_ORG_ID = credentials('tyk-org-id')
        TYK_DASH_SECRET = credentials('tyk-dash-secret')
        TYK_PROD_DASH_URL = credentials('tyk-prod-dash-url')
        TYK_PROD_DASH_SECRET = credentials('tyk-prod-dash-secret')
        TYK_SYNC_PATH = credentials('tyk-sync-path')
    }

    stages {
        stage('test') {
            steps {
                echo 'tests running'
                sh 'ls -al'
                sh env.TYK_SYNC_PATH + 'tyk-sync sync --dashboard ' + env.TYK_DASH_URL + ' --secret ' + env.TYK_DASH_SECRET + ' --path="./dump" --test'
                script {
                    def apiDefs = findFiles(glob: '**/dump/api-*.json')

                    apiDefs.each { apiDef ->
                        def pJson = readJSON file: env.WORKSPACE + "/dump/" + apiDef.name
                        sh "echo Testing ${pJson.name}: ${pJson.api_id}"

                        println "ensuring api is authenticated"
                        assertAuthenticated(pJson)

                        println "ensuring api has appropriate tags"
                        assertWhitelistedTag(pJson)
                    }
                }
            }
        }
        stage('deploy') {
            when {
                expression { env.BRANCH_NAME == 'master' }
            }
            steps {
                echo "Deploying, because we are on ${env.BRANCH_NAME}"
                sh "${env.TYK_SYNC_PATH}tyk-sync sync --dashboard ${env.TYK_DASH_URL} --secret ${env.TYK_DASH_SECRET} --org ${env.TYK_ORG_ID} --path ./dump"
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}

def static assertAuthenticated(api) {
    assert api.use_keyless == false : "api ${api.name} should have authentication enabled"
}

def static assertWhitelistedTag(api) {
    assert api.tags.size() > 0 : "api ${api.name} all APIs should be tagged"

    api.tags.each { tag ->
        assert ["edge"].contains(tag) : "api ${api.name} contains unknown tag ${tag}"
    }
}
